#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if ! [[ -s ~/.config/ziti/ziti-cli.json ]]
then
    fail-message "ziti CLI not logged in"
fi

if ! ziti edge show config "hello-intercept" &>/dev/null
then
    fail-message "config 'hello-intercept' not created"
fi

if ! ziti edge show config "hello-host" &>/dev/null
then
    fail-message "config 'hello-host' not created"
fi

if ! [[ $(ziti edge list services 'name="hello-service"' --output-json | jq '.data|length') -eq 1 ]]
then
    fail-message "service 'hello-service' not created"
fi
