#!/bin/bash
set -euxo pipefail

echo "Running track setup script on host docker-vm"

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# 
sudo apt-get update
sudo apt install -y apt-transport-https ca-certificates curl software-properties-common unzip
# add GPG
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
# add docker to APT sources
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
# update APT
sudo apt update
apt-cache policy docker-ce

# install docker-ce
sudo apt install -y docker-ce
docker version > .docker_version.txt

# install docker compose plugin
sudo apt-get update
sudo apt-get install -y docker-compose-plugin
docker compose version > .docker_compose_version.txt

# create an openziti work directory
mkdir openziti
set-workdir /openziti
cd openziti

# download the docker-compose file
curl -so docker-compose.yaml https://get.openziti.io/dock/docker-compose.yml

# download the config file
curl -so .env https://get.openziti.io/dock/.env

#docker compose --project-name docker up -d

